### ISSUE TITLE
Snow Melting?

### ISSUE THREAD

**Issue by RedZephon** [kangarko/Winter#29]
How long does it take for snow to start melting once that settings has been turned on int he config?

**Comment by kangarko** [comment]
Right now according to the same conditions as Terrain_Generation settings. You can also use our inbuilt command to completely remove all snow from your world and its saved chunks.

**Comment by game1533** [comment]
Hi, whats the command? The snow and the snowman start bringing lags to my server. Can I remove everything at once?

**Comment by kangarko** [comment]
It's "/wt snow" :)

**Comment by game1533** [comment]
The winter snow command just let me see the particles

**Comment by kangarko** [comment]
Pardon, then it's /winter populate

**Comment by game1533** [comment]
ah thanks but this command just increased my file size from 3gb to 8gb and nearly removed most of the snow

**Comment by kangarko** [comment]
It will remove all snow found since there's no difference between Winter's snow and natural snow. I can't tell why it did increase your disk size, because we only remove snow and not add any new blocks.

**Comment by kangarko** [comment]
You can use WorldGuard to trim your worlds afterwards.

**Comment by game1533** [comment]
I was wondering, too. Cause it just removes blocks instead of add more. But thanks. Idk if I should write this in this thred, but I have another little issue with the snow golems. Cause the snow removement process wasnt very successfull on my server backup I just let the winter plugin and used the melting feature. But the snowgolems are still spawning. So I used the Multiverse plugin to stop them from spawning with /mv modify add snow_golems animals. It works. But after a while they keep spawning in certain areas. Do they stop spawning when I disable the Winter plugin? Cause I need it to melt the snow, but if its the case I should remove it cause the snow golems keep adding snow to my worls. Its a bit paradox.

**Comment by kangarko** [comment]
To snow snowmen you need to set Snowman.Transform.Enabled to false and also Snowman.Psycho.Convert_New and Convert_Existing to false in settings.yml, or disable Winter.

**Comment by game1533** [comment]
Ok, thank you, I'll tell you if I spot some snowmen
