### ISSUE TITLE
[Feature Request] Reduced Fall Damage on Snow

### ISSUE THREAD

**Issue by HenrikoMagnifico** [kangarko/Winter#39]
This is a feature that would increase the immersion and usefulness of snow in the plugin. By making the player take reduced fall damage whilst falling onto snow, it brings both increased utility for snow (since it can be used to decrease fall damage of players and mobs) as well as improved realism, since snow does indeed help lessen the impact of falls in the real world as well. There are already several alternative ways to reduce fall damage in Minecraft, like hay bales, beds, water, slime blocks, cobwebs or even the recently added powdered snow. However, none of these are ideal since these options only reduce your damage by either 80% (hay bales), 50% (beds) or 100% (water, cobwebs, ladders). And neither of these options are really aesthetically pleasing, unless used in very particular instances. Snow would look much nicer and blend in better in a wide variety of scenes, especially in a wintery environment, in that regard. It would also make exploring the new extremely high lofty peaks a little less punishing whilst climbing them.

**Comment by yellow-pillow** [comment]
damn, it changes the WHOLE mechanics of minecraft, I don't think it's even possible

and rebuilding mechanics = load on the server


because you will have to track every jump and where it will happen...

and you also don't take into account the fact that after the end of winter you will disable the plugin and the snow mechanics will return to the previous parameters and your players will start dying jumping on the snow thinking that they will not be harmed...

**Comment by kangarko** [comment]
Thanks, but I feel like this would have a performance impact as yellow has suggested beyond tolerable, plus just added overhead for server owners and you are the first suggesting this since 2017, so no thank you.
