### ISSUE TITLE
1.21.3 Certain range dated signs only available on the start date

### ISSUE THREAD

**Issue by x1p** [kangarko/Winter#91]
Certain ranged dated signs are only available on the start date

How to reproduce:
- Make a chest with a sign containing:
```
[Dated]
2.12-30.12
```
- Test player tries to open chest.
- See message: `This chest is only accessible on 2.12`

Try the same with `1.12-30.12` and chest will message `between 1.12 and 30.12`
This is what is expected.

Full list of dated sign which glitch: 
2.12 (as stated above)
9.12
16.12
23.12

Bugged sign:
![2024-11-30_13 01 27](https://github.com/user-attachments/assets/ef355b91-0899-4b2a-92a4-28aa25ab50b4)
Normal working sign
![2024-11-30_13 04 05](https://github.com/user-attachments/assets/f63d4051-c572-444c-9093-3d4912cd83db)

Edit:
The pattern in all of this is that all bugged dates are (a multiple of) 7 days apart.
Example: 30 - 23 =7
Example: 30 - 16 = 14
So making a sign with the dates `24.12-31.12` will also bug

**Comment by kangarko** [comment]
Hey!

Thanks for discovering this bug. Turns out when I wrote this very code in 2017 (!) I mistakenly used getDay() which returns 0 to 7 in Java for week dates instead of getDate() which is the right call.

This bug should have been only decorational and the actual chest opening should have continue to function as intended.

That being said I fixed it!

Matej
