### ISSUE TITLE
Winter causing significant lag

### ISSUE THREAD

**Issue by DarkChromaMC** [kangarko/Winter#95]
Version: 1.21.1

The current situation is the Winter plugin is causing significant lag on my server as demonstrated by my spark report:
https://spark.lucko.me/ct61dQEHLi

The desired solution is for the plugin to be optimized so it doesn't cause lag.

Plugin folder is attached

Thank you for looking into this!

[Winter-2024-12-02T024752Z.tar.gz](https://github.com/user-attachments/files/17971910/Winter-2024-12-02T024752Z.tar.gz)

**Comment by kangarko** [comment]
Hello,

Please optimize your Snow key in settings.yml, namely you need to increase Period_Ticks , I recommend to 4, and reduce Amount to 15 and play with Range, try smaller numbers such as 12 or even 10

**Comment by kangarko** [comment]
For context, every time we spawn a particle we need to find a suitable location, which we find by looking for a suitable air block, for that we need to call Paper API to check the block type. 

Since you have more players on your server, this operation easily multiplies into thousands and therefore it shows in the spark report. I do not think there is any other way other than spawning the particles dump around the players including inside blocks, I can add that option if you want but it might look odd.

**Comment by DarkChromaMC** [comment]
Thanks for the explanation
