### ISSUE TITLE
Snow generation conflicting with vanilla snow

### ISSUE THREAD

**Issue by DarkChromaMC** [kangarko/Winter#96]
Version: 1.21.1
Plugin version: 4.1.3

I have the snow generation disabled but when vanilla snow spawns in cold biomes, due to the plugin, it causes snow generation to occur in areas it shouldn't. Including snow landing on fence posts, item frames and other misc blocks.

The desired solution is the Winter plugin does not interfere with natural vanilla snow generation.

![image](https://github.com/user-attachments/assets/7273af8c-973e-4451-91ea-fe3aab942638)
[Winter-2024-12-02T024752Z.tar.gz](https://github.com/user-attachments/files/17971924/Winter-2024-12-02T024752Z.tar.gz)

**Comment by kangarko** [comment]
Please put all the blocks on which you prefer snow not generation in Terrain.Snow_Generation.Do_Not_Place_On key in settings.yml.

**Comment by DarkChromaMC** [comment]
I'm trying to explain that snow generation is disabled on my server. In the Winter plugin configuration, I have the following setting:

```
Snow_Generation:
  # Randomly places snow on blocks around the player.
  # * This must be enabled if you want to MELT your snow. *
  Enabled: false
```

Despite this setting being disabled, when it naturally rains or snows in cold biomes in the Minecraft world, the Winter plugin interjects itself. It overrides vanilla Minecraft's behavior, causing snow to pile on blocks where it normally wouldn't.

The solution I'm looking for to fix this bug is to let vanilla Minecraft weather patterns (like rain and snow) continue as usual without the Winter plugin overriding them.

**Comment by kangarko** [comment]
Oh I see, I am sorry for the misreading!

Regardless, I can't reproduce this. I used your winter settings and tp'd to ice spikes but no snow was placed on top of fence posts:

![a](https://i.imgur.com/EhgAjNO.png)

The only way we add snow is through a task which is not even run in code when the toggle is off:

![a](https://i.imgur.com/D20kZ7D.png)

Unless you used plugman or reloaded Winter to disable this command, it is not coming from our plugin. I assume you since have done a clean server restart, does it still occur? If yes do a /winter debug instead so I can see which plugins are running.
